# Generated by Django 2.0 on 2017-12-29 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database_meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=264)),
                ('price', models.CharField(max_length=264)),
                ('hot_or_cold', models.CharField(max_length=264)),
                ('cuisine_type', models.CharField(max_length=264)),
                ('meal_category', models.CharField(max_length=264)),
                ('cooking_method', models.CharField(max_length=264)),
                ('meat_1', models.CharField(max_length=264)),
                ('meat_2', models.CharField(max_length=264)),
                ('meat_3', models.CharField(max_length=264)),
                ('carbs_1', models.CharField(max_length=264)),
                ('carbs_2', models.CharField(max_length=264)),
                ('veggie_1', models.CharField(max_length=264)),
                ('veggie_2', models.CharField(max_length=264)),
                ('veggie_3', models.CharField(max_length=264)),
                ('dairy_1', models.CharField(max_length=264)),
                ('dairy_2', models.CharField(max_length=264)),
                ('dairy_3', models.CharField(max_length=264)),
                ('dairy_4', models.CharField(max_length=264)),
                ('gluten_free', models.CharField(max_length=264)),
                ('halal', models.CharField(max_length=264)),
                ('flavouring', models.CharField(max_length=264)),
                ('restaurant_ID', models.CharField(max_length=264)),
            ],
        ),
    ]
