# Generated by Django 2.0 on 2017-12-29 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Database_meal',
            new_name='Database_meals',
        ),
    ]
