# Generated by Django 2.0 on 2017-12-29 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0003_auto_20171230_1040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meals_local_db',
            options={'verbose_name': 'meals_local_db'},
        ),
    ]
