# Generated by Django 2.0 on 2017-12-29 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0005_auto_20171230_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meals_local_db',
            options={'verbose_name': 'meals local database', 'verbose_name_plural': 'meals_local_db'},
        ),
    ]
