# Generated by Django 2.0 on 2017-12-29 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0006_auto_20171230_1046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meals_local_db',
            options={'verbose_name_plural': 'meals local database'},
        ),
    ]
