# Generated by Django 2.0 on 2017-12-29 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userstats_local_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=264)),
                ('search_time', models.CharField(max_length=264)),
                ('search_date', models.CharField(max_length=264)),
                ('search_frequency', models.CharField(max_length=264)),
                ('search_time_mean', models.CharField(max_length=264)),
                ('search_time_stddev', models.CharField(max_length=264)),
                ('search_date_interval_mean', models.CharField(max_length=264)),
                ('search_date_interval_stddev', models.CharField(max_length=264)),
                ('meat_last_1', models.CharField(max_length=264)),
                ('meat_last_2', models.CharField(max_length=264)),
                ('meat_last_3', models.CharField(max_length=264)),
                ('veggie_last_1', models.CharField(max_length=264)),
                ('veggie_last_2', models.CharField(max_length=264)),
                ('veggie_last_3', models.CharField(max_length=264)),
                ('carbs_last_1', models.CharField(max_length=264)),
                ('carbs_last_2', models.CharField(max_length=264)),
                ('dairy_last_1', models.CharField(max_length=264)),
                ('dairy_last_2', models.CharField(max_length=264)),
                ('dairy_last_3', models.CharField(max_length=264)),
                ('gluten_free_last', models.CharField(max_length=264)),
                ('halal_last', models.CharField(max_length=264)),
                ('flavouring_last', models.CharField(max_length=264)),
                ('restaurant_ID_last', models.CharField(max_length=264)),
            ],
            options={
                'verbose_name_plural': 'userstats local database',
            },
        ),
    ]
