# Generated by Django 2.0 on 2017-12-30 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userstats_local_db',
            new_name='usage_stats_local_db',
        ),
        migrations.AlterModelOptions(
            name='usage_stats_local_db',
            options={'verbose_name_plural': 'usage stats local database'},
        ),
    ]
