# Generated by Django 2.0 on 2017-12-30 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats_app', '0002_auto_20171230_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usage_stats_local_db',
            old_name='carbs_last_1',
            new_name='carbs_1_last',
        ),
        migrations.RenameField(
            model_name='usage_stats_local_db',
            old_name='carbs_last_2',
            new_name='carbs_2_last',
        ),
        migrations.RenameField(
            model_name='usage_stats_local_db',
            old_name='dairy_last_1',
            new_name='dairy_1_last',
        ),
        migrations.RenameField(
            model_name='usage_stats_local_db',
            old_name='dairy_last_2',
            new_name='dairy_2_last',
        ),
        migrations.RenameField(
            model_name='usage_stats_local_db',
            old_name='dairy_last_3',
            new_name='dairy_3_last',
        ),
        migrations.RenameField(
            model_name='usage_stats_local_db',
            old_name='meat_last_1',
            new_name='meat_1_last',
        ),
        migrations.RenameField(
            model_name='usage_stats_local_db',
            old_name='meat_last_2',
            new_name='meat_2_last',
        ),
        migrations.RenameField(
            model_name='usage_stats_local_db',
            old_name='meat_last_3',
            new_name='meat_3_last',
        ),
        migrations.RenameField(
            model_name='usage_stats_local_db',
            old_name='veggie_last_1',
            new_name='veggie_1_last',
        ),
        migrations.RenameField(
            model_name='usage_stats_local_db',
            old_name='veggie_last_2',
            new_name='veggie_2_last',
        ),
        migrations.RenameField(
            model_name='usage_stats_local_db',
            old_name='veggie_last_3',
            new_name='veggie_3_last',
        ),
    ]
